[general]
version = 1

[[segment]]

[[segment.mempool]]
size = 1024
count = 50000

[[segment.mempool]]
size = 2048
count = 100000

[[segment.mempool]]
size = 4096
count = 5000

[[segment.mempool]]
size = 16384
count = 1000

[[segment.mempool]]
size = 32768  
count = 2000

[[segment.mempool]] 
size = 65536 
count = 1000

[[segment.mempool]]
size = 1048576 
count = 20

[[segment.mempool]]
size = 8388608
count = 5






